// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

// Injectors from wire.go:

func InitWork(p PlayParam, n MonParam) Work {
	play := NewPlay(p)
	mon := NewMon(n)
	work := NewWork(play, mon)
	return work
}
